$$
\newcommand{theorem}{\textbf{Theorem: }}
\newcommand{proof}{\textbf{Proof: }}
\newcommand{lemma}{\textbf{Lemma: }}
\newcommand{corollary}{\textbf{Corollary: }}
\newcommand{prop}{\textbf{Proposition: }}
$$

$$
\newcommand{arr}{\mathbf}
\newcommand{inv}{^{-1}}
\newcommand\mat[1]{\begin{pmatrix}#1\end{pmatrix}} 
\newcommand\det[1]{\left| #1\right|} 
\newcommand\norm[1]{\lVert #1\rVert} 
\newcommand\set[1]{\left\{#1\right\}} 
$$

In [1]:
import numpy as np
from module.matrix import mult, inv

# Diagonalization

A square matrix $\arr A$ is **diagonalizable** if there exists an invertible matrix $\arr P$ such that $\arr P \inv \arr A \arr P = \arr D$ is a diagonal matrix.

In other words, $\arr A = \arr {PDP} \inv$, for some diagonal matrix $\arr D$.

$\lemma$ $\arr D$ will contain the eigenvalues of $\arr A$.

<details>
<summary style="color: blue">$\proof$ (Click to expand)</summary>
    <div style="background: aliceblue">
        We consider the characteristic polynomial of $\arr A$:
        $$
        \begin{align}
        \det{x \arr I - \arr A} &= \det{x \arr I - \arr {PDP}\inv} \\
        &= \det{x \arr {PP} \inv - \arr {PDP} \inv} \\
        &= \det{\arr P (x \arr I - \arr D) \arr P \inv} \\
        &= \det{\arr P} \det {x \arr I - \arr D} \det {\arr P \inv} \\
        &= \det{x \arr I - \arr D}
        \end{align}
        $$
        Hence, $\arr A$ and $\arr D$ have the same characteristic polynomial, and hence the same eigenvalues.
        Since $\arr D$ is diagonal, we know that its (diagonal) entries are its eigenvalues.
        $$QED$$
    </div>
</details>

$\theorem$ Given a square matrix $\arr A$, $\arr A$ is diagonalizable if and only if there exists a basis $\set{\arr u_1, \dots, \arr u_n}$, where $\arr u_i \in \mathbb R^n$ are all eigenvectors of $\arr A$.

Proof is omitted.

In other words, if $\arr A$ is diagonalizable, it can be expressed as $\arr {PDP} \inv$, where $\arr D$ is a diagonal entries with its eigenvalues, and $\arr P$ which are horizontally stacked columns of the eigenvectors of $\arr A$, and the eigenvector of each column correspond to the eigenvector in the same column of $\arr D$.

**Example** 

Given $\arr A = \mat{1 & 1 & 0 \\ 1 & 1 & 0 \\ 0 & 0 & 2}$.

We can compute its eigenvalues to be $0$ and $2$.

The bases are $E_0 = \set{\mat{-1 \\ 1 \\ 0}}, E_2 = \set{\mat{1 \\ 1 \\0},\mat{0 \\ 0 \\ 1}}$.

Thus, we simply stack the columns to get $\arr P = \mat{-1 & 1 & 0 \\ 1 & 1 & 0 \\ 0 & 0 & 1}$.

And $\arr D = \mat{0 & 0 & 0 \\ 0 & 2 & 0 \\ 0 & 0 & 2}$.

Putting it together, we get $$\arr A =  \mat{-1 & 1 & 0 \\ 1 & 1 & 0 \\ 0 & 0 & 1}\mat{0 & 0 & 0 \\ 0 & 2 & 0 \\ 0 & 0 & 2} \mat{-1 & 1 & 0 \\ 1 & 1 & 0 \\ 0 & 0 & 1} \inv$$.

In [2]:
P = np.array([-1, 1, 0, 1, 1, 0, 0, 0, 1]).reshape((3, 3))
D = np.diag([0, 2, 2])

In [3]:
mult(P, mult(D, inv(P)))

array([[1., 1., 0.],
       [1., 1., 0.],
       [0., 0., 2.]])

For $\arr A = \mat{1 & 2 \\ 0 & 1}$.
We can see that the eigenvalue is $\lambda = 1$ with multiplicity of 2.
However, there is only 1 eigenvector associated with the eigenvalue, $\mat{ 1 \\ 0}$, and hence we are unable to diagonalize $\arr A$.

$\theorem$ The geometric multiplicity of any eigenvector is at most its algebraic multiplicity.

$\theorem$ $\arr A$ is diagonalizable if and only if the geometric multiplicity of all eigenvectors is equals to its algebraic multiplicity.

Hence, it tells us there that are 2 requirements for a matrix to be diagonalizable:
1. It has to have sufficient number of (real) eigenvalues, so that we can fill up $\arr D$.
2. It has to have sufficient number of eigenvectors, so that we can fill up $\arr A$.
    * This is related to the geometric multiplicity being equals to the algebraic multiplicity

$\corollary$ Any square matrix of order $n$ with $n$ distinct eigenvalues is diagonalizable.

## Orthogonal diagonalization

A square matrix is known as an **orthogonal matrix** if $\arr A^T = \arr A \inv$.

$\theorem$ The following statements are equivalent, for $\arr A$, a square matrix of $\arr n$:
1. $\arr A$ is orthogonal
2. The columns of $\arr A$  forms a orthonormal basis for $\mathbb R^n$
2. The rows of $\arr A$  forms a orthonormal basis for $\mathbb R^n$

<details>
<summary style="color: blue">$\proof$ (Click to expand)</summary>
    <div style="background: aliceblue">
        We express $$\arr A = \mat{\arr c_1 & \dots & \arr c_n}$$
        Now notice that $\arr A ^T \arr A = \mat{\arr c_1^T \\ \vdots \\ \arr c_n^T} \mat{\arr c_1 & \dots & \arr c_n}$
        <br>
        Hence, the $ij$-th entry of $\arr A^T \arr A$ is $c_i^T c_j =  c_i \cdot c_j$.
        <br>
        Hence, $\arr A ^T = \arr A \inv \Leftrightarrow \arr A^T \arr A = \arr I \Leftrightarrow c_i \cdot c_j = \begin{cases} 1, \quad i = j \\ 0, \quad i \neq j\end{cases} \Leftrightarrow $ columns of $\arr A$ is an orthonormal basis.
        <br>
        We have proven statement 1 to 2, and can do similarly for 1 to 3.
        $$QED$$
    </div>
</details>

A square matrix $\arr A$ is **orthogonally diagonalizable** if 
$$
\arr A = \arr {PDP}^T
$$

$\theorem$ A square matrix is orthogonally diagonalizable if and only if it is symmetric


<details>
<summary style="color: blue">$\proof$ (Click to expand)</summary>
    <div style="background: aliceblue">
        Suppose that it is orthogonally diagonalizable, then
        $$
        \arr A ^T = (\arr {PDP}^T)^T = (\arr P^T)^T \arr D^T \arr P^T = \arr P \arr D \arr P^T = \arr A
        $$
        Hence it is symmetric.
        The proof for the converse is omitted as it is beyond the scope of this course.
        $$QED$$
    </div>
</details>

To orthogonally diagonalize a matrix, we simply do similar to diagonalizing a matrix, except that for each eigenvalue, we perform the [Gram-Schmidt process](./orthogonal_projection.ipynb#Gram-Schmidt-process) on the associated eigenvectors to obtain an orthonormal basis for the eigenspace.

**Example** 

Using our previous example of $\arr A = \mat{1 & 1 & 0 \\ 1 & 1 & 0 \\ 0 & 0 & 2}$.

The bases are $E_0 = \set{\mat{-1 \\ 1 \\ 0}}, E_2 = \set{\mat{1 \\ 1 \\0},\mat{0 \\ 0 \\ 1}}$.

The orthonormal bases are $E_0 = \frac{1}{\sqrt 2} \set{\mat{-1 \\ 1 \\ 0}}, E_2 = \set{\frac{1}{\sqrt 2}\mat{1 \\ 1 \\0},\mat{0 \\ 0 \\ 1}}$.

Putting it together, we get $$\arr A =  \mat{-\frac{1}{\sqrt 2} & \frac{1}{\sqrt 2} & 0 \\ \frac{1}{\sqrt 2} & \frac{1}{\sqrt 2} & 0 \\ 0 & 0 & 1}\mat{0 & 0 & 0 \\ 0 & 2 & 0 \\ 0 & 0 & 2}\mat{-\frac{1}{\sqrt 2} & \frac{1}{\sqrt 2} & 0 \\ \frac{1}{\sqrt 2} & \frac{1}{\sqrt 2} & 0 \\ 0 & 0 & 1} ^T $$.

($\arr P$ happened to be symmetric)

In [4]:
isqrt = 1/np.sqrt(2)
P = np.array([-isqrt, isqrt, 0, isqrt, isqrt, 0, 0, 0, 1]).reshape((3 , 3))
P, inv(P)

(array([[-0.70710678,  0.70710678,  0.        ],
        [ 0.70710678,  0.70710678,  0.        ],
        [ 0.        ,  0.        ,  1.        ]]),
 array([[-0.70710678,  0.70710678,  0.        ],
        [ 0.70710678,  0.70710678,  0.        ],
        [ 0.        ,  0.        ,  1.        ]]))

Indeed, we see that $\arr P ^T = \arr P \inv$

In [5]:
D = np.diag([0, 2, 2])
mult(P, mult(D, P.T))

array([[1., 1., 0.],
       [1., 1., 0.],
       [0., 0., 2.]])

And we can see that $\arr A = \arr{PDP}^T$.

## Application

### Matrix exponentiation

We can use diagonalization to perform raising a matrix to a power.

$\lemma$ If $\arr A = \arr {PDP} \inv$, then $\arr A^m = \arr P \arr D^m \arr P \inv$.

$\lemma$ Let the diagonal entries $\arr D$ be $d_1, \dots, d_n$, then $\arr D^m$ is also diagonal, with entries $d_1 ^m, \dots, d_n^m$.

Hence, we have found an easy way to compute a large power of a matrix.

**Example**

Using our previous example of $\arr A = \mat{1 &  1 & 0 \\ 1 & 1 & 0 \\ 0 & 0 & 2}$.

Suppose that we want to compute $\arr A ^{20}$.

Rather than performing many matrix multiplications, we can instead compute
$$
\arr A ^{20} = \arr P \arr D^{20} \arr P \inv
= \mat{-1 & 1 & 0 \\ 1 & 1 & 0 \\ 0 & 0 & 1}\mat{0 & 0 & 0 \\ 0 & 2^{20} & 0 \\ 0 & 0 & 2^{20}} \mat{-1 & 1 & 0 \\ 1 & 1 & 0 \\ 0 & 0 & 1} \inv
$$

In [6]:
P = np.array([-1, 1, 0, 1, 1, 0, 0, 0, 1]).reshape((3, 3))
D20 = np.diag([0, 2**20, 2**20])
mult(P, mult(D20, inv(P)))

array([[ 524288.,  524288.,       0.],
       [ 524288.,  524288.,       0.],
       [      0.,       0., 1048576.]])

In [7]:
m = 20

A = np.array([1,1, 0, 1, 1, 0, 0, 0, 2]).reshape((3, 3))
Am = A
for _ in range(1, m):
    Am = mult(Am, A)
    
Am

array([[ 524288.,  524288.,       0.],
       [ 524288.,  524288.,       0.],
       [      0.,       0., 1048576.]])

Indeed, we get the same results when we use our diagonalization and when we perform the repeated multiplications.

---

In fact, matrix exponentiation usually props up when we are working with recursive formulas, such as linear recurrence or Markov chains.

#### Linear recurrence

The Fibonacci sequence is as follows:
$$
(0), 1, 1, 2, 3, 5, 8, 13, \dots
$$
where each element is the sum of the previous two.
(Note that $a_0 = 0$, but the start of the sequence is $a_1 = 1$)

We can represent it as the following matrix equation:

$$
\mat{a_n \\ a_{n+1}} = \mat{0 & 1\\ 1 & 1}\mat{a_{n-1} \\ a_n}
$$

Notice that $\mat {a_n \\ a_{n+1}} = \mat{0 & 1 \\ 1 & 1}^n \mat{0 \\ 1}$

Diagonalizing $\arr A = \mat{0 & 1\\ 1 & 1}$.

$char (\arr A) = x(x-1) -1 = x^2 - x -1$.

The eigenvalues are $\lambda_a = \frac{1 + \sqrt 5}{2}, \lambda_b = \frac{1 - \sqrt 5}{2}$, with the eigenvectors of $\mat{1 \\ \lambda _a}, \mat{1 \\ \lambda_b}$ respectively.

Hence, $\arr A = \arr {PDP} \inv = \mat{1 & 1 \\ \lambda_a & \lambda_b} \mat{\lambda _a & 0 \\ 0 & \lambda _b}\mat{1 & 1 \\ \lambda_a & \lambda_b}\inv$

Thus, $\arr A^n \mat{0 \\ 1} = \arr {PDP} \inv = \mat{1 & 1 \\ \lambda_a & \lambda_b} \mat{\lambda _a^n & 0 \\ 0 & \lambda _b^n}\mat{1 & 1 \\ \lambda_a & \lambda_b}\inv \mat{0 \\1}$

Expanding the first row, we get that 
$$
a_n = \frac{\lambda _a ^n - \lambda _b ^n}{\lambda_a - \lambda_b}
$$

In [8]:
la = (1 + np.sqrt(5)) /2
lb = (1 - np.sqrt(5)) /2

n = 50
(la ** n - lb **n)/(la - lb)

12586269025.00002

In [9]:
def f(n):
    a, b = 1, 1
    for _ in range(1, n):
        a, b = b, a + b
        
    return a
f(n)

12586269025

Indeed, our close form formula yielded the same answer (albeit with some floating point inaccuracies) as the iterative solution.

##### Application to algorithms

Recall that in algorithm analysis, we perform [quick integer exponentiation](../algorithm_analysis/recursion.ipynb#Exponentiation).
We can use similar technique to perform quick matrix exponentiation.
So instead of using the closed form formula (which have floating point errors), we instead perform matrix exponentiation on $\mat{0 & 1 \\ 1 &1}$.

In [10]:
def exp(A, n, mod=1000000007):
    if n == 1:
        return A
    
    m = n//2
    e = exp(A, m, mod)
    sqr = mult(e, e)
    
    if n % 2 == 0:
        return sqr % mod
    else:
        return mult(sqr, A) % mod

In [11]:
def exp_fib(n, m=1000007):
    A = np.array([0, 1, 1, 1]).reshape((2, 2)).astype('int')
    An = exp(A, n, m)
    an, _ = mult(An, np.array([0, 1]).reshape((2, 1))).ravel()
    return int(an)

In [12]:
def fib(n, mod=1000007):
    a, b = 1, 1

    for _ in range(1, n):
        a, b = b % mod, a + b % mod
        
    return a

Since our numbers can get ridiculously big when $n$ is large, we perform a modulo operation to prevent our numbers from becoming too large for our program to handle.
This allows us to check for correctness of our algorithm against the typical algorithm, while allowing us to compare the performance of the two.

In [13]:
n=int(1e6)
exp_fib(n), fib(n)

(930254, 930254)

Notice that we obtain the same exact results.

In [14]:
%timeit -n10 exp_fib(n)

1.32 ms ± 254 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [15]:
%timeit -n10 fib(n)

75.3 ms ± 1.08 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


But we computed it significantly faster.

Hence, we can actually compute the (exact) Fibonacci number in $O(\log n)$.